# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Personal Web Site
title-name: Franco Sterrantino
# Description of the Site
description: Data Analyst/Engineer
# URL of Image of the Site
site-image: /assets/images/meta.jpg
# Keywords of the Site
site-keywords: Personal-site, Franco, Sterrantino, CV, Portfolio
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: francosterrantino@gmail.com
facebook_username: None
twitter_username: fsterrantino
instagram_username: None
linkedin_username: franco-sterrantino-19417195
github_username:  fsterrantino
youtube_channel_id: None
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: ""

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Franco_Sterrantino
# URL for the Image of the Author
author-image: /assets/images/franco_cv.jpg
# 60 Words About the Author
author-about: Hi, my name is Franco and I'm an Industrial Engineer. Despite my professional carreer in Technological and Operational Risk Management, I am embarking on a deliberate career pivot towards Data Analysis/Engineering, a field that has captivated my interest and driven me to craft projects as a hobbyist. My extensive experience in Operational Risk, in the financial industry, has cultivated a robust sense of business processes, ideal to understand diverse team requirements, and a profound ability to bridge business needs with technical solutions.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/fsterrantino
# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
